[project]
name = "pipex"
version = "1.0.0"

[submit]
files = [
	# C sources
	"_main*.c",
	"app_*.c",
	"args_*.c",
	"bonus_here_doc.c",
	"cmda_*.c",
	"env_*.c",
	"exec_*.c",
	"*find_bin.c",
	# C headers
	"*.h",
	# Other
	"Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = ["."]

[submit.hooks]
pre_submit = "make fclean > /dev/null"

[submit.validation]
norminette = true

######## Ft_printf #########
[[submit.copy]]
source = "../milestone-1-ft_printf/Makefile"
destination = "ft_printf"

[[submit.copy]]
source = "../milestone-1-ft_printf/ft_printf.h"
destination = "ft_printf"

[[submit.copy]]
source = "../milestone-1-ft_printf/ft_printf.c"
destination = "ft_printf"
[[submit.copy]]
source = "../milestone-1-ft_printf/ft_putchar.c"
destination = "ft_printf"
[[submit.copy]]
source = "../milestone-1-ft_printf/ft_putnbr_base_ssize.c"
destination = "ft_printf"
[[submit.copy]]
source = "../milestone-1-ft_printf/ft_putstr_ssize.c"
destination = "ft_printf"

########### Lift ###########
[[submit.copy]]
source = "../milestone-0-libft/Makefile"
destination = "libft"

[[submit.copy]]
source = "../milestone-0-libft/libft.h"
destination = "libft"

[[submit.copy]]
source = "../milestone-0-libft/ft_abs.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_atoi.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_bzero.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_calloc.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_env_find.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_isalnum.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_isalpha.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_isascii.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_isdigit.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_isprint.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_isspace.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_itoa.c"
destination = "libft"

[[submit.copy]]
source = "../milestone-0-libft/ft_lstadd_back_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstadd_front_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstclear_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstdelone_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstiter_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstlast_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstmap_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstnew_bonus.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_lstsize_bonus.c"
destination = "libft"

[[submit.copy]]
source = "../milestone-0-libft/ft_memchr.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_memcmp.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_memcpy.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_memmove.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_memset.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_putchar_fd.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_putendl_fd.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_putnbr_fd.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_putstr_fd.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_recalloc.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_split.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strchr.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strcmp.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strdup.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_striteri.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strjoin.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strlcat.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strlcpy.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strlen.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strmapi.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strncmp.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strnstr.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strrchr.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_strtrim.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_substr.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_tolower.c"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/ft_toupper.c"
destination = "libft"

########### GNL ###########
[[submit.copy]]
source = "../milestone-1-get_next_line/Makefile"
destination = "get_next_line"

[[submit.copy]]
source = "../milestone-1-get_next_line/get_next_line.h"
destination = "get_next_line"

[[submit.copy]]
source = "../milestone-1-get_next_line/get_next_line.c"
destination = "get_next_line"
[[submit.copy]]
source = "../milestone-1-get_next_line/get_next_line_utils.c"
destination = "get_next_line"
