[project]
name = "get_next_line"
version = "1.0.0"

[submit]
files = [
  "get_next_line.h",
  "*.c",
  "Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = [".", ".."]

[submit.hooks]
pre_submit = "make fclean > /dev/null"

[submit.validation]
norminette = true

# **************************************************************************** #
#                                    LibFt                                     #
# **************************************************************************** #
[[submit.copy]]
source = "../milestone-0-libft/Makefile"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/*.{c,h}"
destination = "libft"
