[project]
name = "push_swap"
version = "0.1.0"

[submit]
files = [
	# C sources
	"args_legit.c",
	"checker.c",
	"checker_utils.c",
	"get_next_line.c",
	"mani_*.c",
	"parse_stdin.c",
	"push_swap.c",
	"sort_*.c",
	"stack_*.c",
	"std_error.c",
	# C headers
	"push_swap.h",
	# Other
	"Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = [".", ".."]

[submit.hooks]
# pre_submit = "make fclean"

[submit.validation]
norminette = true
# make_test = true

# Lift
[[submit.copy]]
source = "../milestone-0-libft/ft_abs.c"
destination = "."
replace = [
	{ find = "libft.h", replace_with = "push_swap.h" }
]
flatten = true

[[submit.copy]]
source = "../milestone-0-libft/ft_atol.c"
destination = "."
replace = [
	{ find = "libft.h", replace_with = "push_swap.h" }
]
flatten = true

[[submit.copy]]
source = "../milestone-0-libft/ft_calloc.c"
destination = "."
replace = [
	{ find = "libft.h", replace_with = "push_swap.h" }
]
flatten = true

[[submit.copy]]
source = "../milestone-0-libft/ft_isdigit.c"
destination = "."
replace = [
	{ find = "libft.h", replace_with = "push_swap.h" }
]
flatten = true

[[submit.copy]]
source = "../milestone-0-libft/ft_isnumber.c"
destination = "."
replace = [
	{ find = "libft.h", replace_with = "push_swap.h" }
]
flatten = true

[[submit.copy]]
source = "../milestone-0-libft/ft_split.c"
destination = "."
replace = [
	{ find = "libft.h", replace_with = "push_swap.h" }
]
flatten = true
