workspace(name = "minilibx_linux")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# If using Nix(OS)
#   This file will be augmented by .bazelrc.local generated by the Nix flake
#   The Nix flake will create a workspace_extra.bzl with library paths
#   You must run bazel inside of the DevShell (`nix run --flake .` or `direnv allow`).
# If using Ubuntu (school computers)
#   The workspace_deps.bzl file will not be created by any script, meaning you
#   must sylink it to workspace_deps_system.bzl.

load("//:workspace_deps.bzl", "load_dependencies")
load_dependencies()
