[project]
name = "philo"
version = "1.1.0"

[submit]
files = [
	"src/*.c",
	"includes/*.h",
	"Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = ["."]

[submit.hooks]
temp_prepare = "mkdir philo && mv Makefile src includes philo/"

[submit.validation]
norminette = true
