[project]
name = "push_swap"
version = "1.0.1"

[submit]
files = [
	"*.c",
	"push_swap.h",
	"Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = ["."]

[submit.hooks]
pre_submit = "make fclean > /dev/null"

[submit.validation]
norminette = true

# **************************************************************************** #
#                                    LibFt                                     #
# **************************************************************************** #
[[submit.copy]]
source = "../milestone-0-libft/Makefile"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/*.{c,h}"
destination = "libft"

# **************************************************************************** #
#                                   FtPrintf                                   #
# **************************************************************************** #
[[submit.copy]]
source = "../milestone-1-ft_printf/Makefile"
destination = "ft_printf"
[[submit.copy]]
source = "../milestone-1-ft_printf/*.{c,h}"
destination = "ft_printf"

# **************************************************************************** #
#                                     GNL                                      #
# **************************************************************************** #
[[submit.copy]]
source = "../milestone-1-get_next_line/Makefile"
destination = "get_next_line"
[[submit.copy]]
source = "../milestone-1-get_next_line/*.{c,h}"
destination = "get_next_line"
