[project]
name = "philo"
version = "1.0.0"

[submit]
files = [
	# C sources
	"src/*.c",
	# C headers
	"includes/*.h",
	# Other
	"Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = ["."]

[submit.hooks]
temp_prepare = "mkdir philo && mv Makefile src includes philo/"

[submit.validation]
norminette = true
