[project]
name = "cpp03"
version = "1.0.0"

[submit]
files = [
  "ex*/*{c,h}pp",
  "ex*/Makefile",
  "ex*/.gitignore"
]

[submit.preprocessor]
enable_gpm = false
function_paths = []

[submit.hooks]
temp_prepare = "echo '*.o' >> .gitignore"

[submit.validation]
norminette = false
