[package]
name = "push_swap_mc_visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
tokio = { version = "1.42.0", features = ["full"] }
valence = { git = "https://github.com/valence-rs/valence" }
