[project]
name = "cpp02"
version = "1.0.0"

[submit]
files = [
  "ex*/*{c,h}pp",
  "ex*/Makefile",
  "ex*/.gitignore",
  ".gigignore"
]

[submit.preprocessor]
enable_gpm = false
function_paths = []

[submit.validation]
norminette = false
