[project]
name = "fdf"
version = "1.0.0"

[submit]
files = [
	# C sources
	"src/*.c",
	# C headers
	"fdf.h",
	# Other
	"Makefile"
]

[submit.preprocessor]
enable_gpm = true
function_paths = ["."]

[submit.hooks]
pre_submit = "make fclean > /dev/null"

[submit.validation]
norminette = true

######## Ft_printf #########
[[submit.copy]]
source = "../milestone-1-ft_printf/Makefile"
destination = "ft_printf"
[[submit.copy]]
source = "../milestone-1-ft_printf/*.{h,c}"
destination = "ft_printf"

########### Lift ###########
[[submit.copy]]
source = "../milestone-0-libft/Makefile"
destination = "libft"
[[submit.copy]]
source = "../milestone-0-libft/*.{h,c}"
destination = "libft"

########### GNL ###########
[[submit.copy]]
source = "../milestone-1-get_next_line/Makefile"
destination = "get_next_line"
[[submit.copy]]
source = "../milestone-1-get_next_line/*.{h,c}"
destination = "get_next_line"

########### MLX ###########
[[submit.copy]]
source = "../extra-minilibx/"
destination = "minilibx"
