name: Make

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.target }} [${{ matrix.os }}-${{ matrix.arch }}]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        target: [libft, ft_printf, push_swap]
        include:
          # Linux builds
          - os: ubuntu-latest
            arch: x86_64
            shell: bash

    steps:
      # Configure Git to handle special characters before checkout
      - name: Configure Git
        shell: bash
        run: |
          git config --global core.protectNTFS false
          git config --global core.quotePath false
          git config --global core.safecrlf false

      # Modified checkout with special handling
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
        env:
          GIT_TEST_DEBUG: 1

      - name: Build ${{ matrix.target }} Linux
        if: runner.os == 'Linux'
        shell: bash
        run: make ${{ matrix.target }}
