name: Make

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'milestone-*/**/*'
      - '.github/workflows/make.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'milestone-*/**/*'
      - '.github/workflows/make.yml'

jobs:
  build:
    name: ${{ matrix.target }} [${{ matrix.os }}-${{ matrix.arch }}]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [x86_64]
        target: [libft, ft_printf, get_next_line, pipex, push_swap, fdf, minishell, philo]
        include:
          # Linux builds
          - os: ubuntu-22.04
            arch: x86_64
            shell: bash

    steps:
      # Configure Git to handle special characters before checkout
      - name: Configure Git
        shell: bash
        run: |
          git config --global core.protectNTFS false
          git config --global core.quotePath false
          git config --global core.safecrlf false

      # Modified checkout with special handling
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
        env:
          GIT_TEST_DEBUG: 1

      - name: Install LibBSD
        if: runner.os == 'Linux'
        shell: bash
        run: sudo apt-get install libbsd-dev

      - name: Build ${{ matrix.target }} Linux
        if: runner.os == 'Linux'
        shell: bash
        run: make ${{ matrix.target }}
