name: Norminette

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'milestone-*/**/*'
      - '.github/workflows/norminette.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'milestone-*/**/*'
      - '.github/workflows/norminette.yml'

jobs:
  norminette:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install norminette
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install norminette

    - name: Run norminette
      run: norminette milestone-{0-libft,1-get_next_line,1-ft_printf,2-pipex,2-push_swap,2-fdf}
