# Docs here: https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Run Release Please
jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{secrets.GH_TOKEN}}

      # Note: Here I stripped the npm publication logic from the original example

