name: Zig CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Zig CI
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v6

    - name: Install system
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxext-dev \
          libreadline-dev \
          nasm

    - name: Install Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.16.0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Zig
      uses: actions/cache@v5
      with:
        path: .zig-cache
        key: ${{ runner.os }}-zig-${{ hashFiles('build.zig', 'build.zig.zon', 'build_helpers.zig') }}
        restore-keys: |
          ${{ runner.os }}-zig-

    - name: Cache Cargo
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('tools/push-swap-visualizer-minecraft/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build All Targets
      run: zig build --global-cache-dir .zig-cache
